# Generated by https://pagedraw.io/pages/11538
React = require 'react'


render = ->
    <div className="backbutton-backbutton-6">
        <style dangerouslySetInnerHTML={__html: """
            @import url('https://fonts.googleapis.com/css?family=Lato:');
            
            .backbutton-backbutton-6 {
                display: flex;
                flex-direction: column;
                flex-grow: 1;
                cursor: pointer;
            }
            
            .backbutton-0 {
                display: flex;
                flex-shrink: 0;
            }
            
            .backbutton-oval-4 {
                display: flex;
                flex-direction: column;
                padding-top: 4px;
                padding-bottom: 4px;
                border-radius: 100%;
                background: rgb(57, 150, 253);
            }
            
            .backbutton-0-0-0 {
                display: flex;
                flex-shrink: 0;
                padding-left: 5px;
                padding-right: 5px;
            }
            
            .backbutton-_-4 {
                width: 16px;
                flex-shrink: 0;
                cursor: pointer;
                font-family: "Lato", sans-serif;
                color: rgb(255, 255, 255);
                font-size: 16px;
                line-height: 18px;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            * {
                box-sizing: border-box;
            }
            
            body {
                margin: 0;
            }
            
            button:hover {
                cursor: pointer;
            }
            
            a {
                text-decoration: none;
                color: inherit;
            }
            
            .pd-onhover-parent >.pd-onhover {
                display: none;
            }
            
            .pd-onhover-parent:hover > * {
                display: none;
            }
            
            .pd-onhover-parent:hover > .pd-onhover {
                display: flex;
            }
            
            .pd-onactive-parent > .pd-onactive {
                display: none;
            }
            
            .pd-onactive-parent:active > * {
                display: none;
            }
            
            .pd-onactive-parent:active > .pd-onactive {
                display: flex;
            }
            
            .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
                display: none;
            }
        """} /> 
        <div className="backbutton-0">
            <div title={"Back to store"} onClick={@props.onClick} className="backbutton-oval-4">
                <div className="backbutton-0-0-0">
                    <div className="backbutton-_-4">{"←"}</div>
                </div>
            </div>
        </div>
    </div>

module.exports = (props) -> render.apply({props})
