# Generated by https://pagedraw.io/pages/11538
React = require 'react'
Publiclibrary = require './publiclibrary'
Createlibrarycard = require './createlibrarycard'


render = ->
    <div className="storefront-storefront-5">
        <style dangerouslySetInnerHTML={__html: """
            @import url('https://fonts.googleapis.com/css?family=Lato:');
            
            .storefront-storefront-5 {
                display: flex;
                flex-direction: column;
                flex-grow: 1;
                padding-top: 20px;
                background: rgb(251, 251, 251);
            }
            
            .storefront-0 {
                display: flex;
                flex-shrink: 0;
                padding-left: 20px;
                padding-right: 20px;
            }
            
            .storefront-0-0 {
                display: flex;
                flex-direction: column;
                padding-top: 3px;
                padding-bottom: 4px;
            }
            
            .storefront-0-0-0 {
                display: flex;
                flex-shrink: 0;
            }
            
            .storefront-icon-7 {
                width: 48px;
                height: 48px;
                flex-shrink: 0;
                background-image: url('https://complex-houses.surge.sh/b6616ada-e508-4815-8765-080ce2920bcc/original');
                background-size: contain;
                background-position: center;
                background-repeat: no-repeat;
            }
            
            .storefront-library_store_-5 {
                width: 701px;
                flex-shrink: 0;
                margin-left: 15px;
                font-family: "Lato", sans-serif;
                color: rgb(0, 0, 0);
                font-size: 48px;
                line-height: 55px;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .storefront-1 {
                display: flex;
                flex-shrink: 0;
                margin-top: 20px;
                padding-left: 20px;
                padding-right: 20px;
            }
            
            .storefront-pagedraw_libraries_allow_you_to_import_existing_react_libraries_straight_into_pagedraw_just_find_a_widget_or_component_library_you_like_add_the_library_to_your_project_and_you_are_ready_to_go_-1 {
                flex-grow: 1;
                flex-basis: 0px;
                font-family: "Lato", sans-serif;
                color: rgb(93, 93, 93);
                font-size: 18px;
                line-height: 21px;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .storefront-2 {
                display: flex;
                flex-shrink: 0;
                margin-top: 40px;
                padding-left: 20px;
                padding-right: 20px;
            }
            
            .storefront-popular_libraries_-5 {
                width: 764px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 36px;
                line-height: 41px;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .storefront-3 {
                display: flex;
                flex-shrink: 0;
                padding-right: 20px;
            }
            
            .storefront-rectangle_1 {
                height: 169px;
                flex-grow: 1;
                flex-basis: 0px;
                overflow: scroll;
                position: relative;
                background: rgba(255, 255, 255, 0);
            }
            
            .storefront-3-0-0 {
                display: flex;
                flex-direction: column;
                flex-grow: 1;
                padding-top: 19px;
                position: absolute;
                width: 100%;
                min-height: 100%;
            }
            
            .storefront-3-0-0-0 {
                display: flex;
                flex-shrink: 0;
                padding-left: 20px;
            }
            
            .storefront-3-0-0-0-0 {
                display: flex;
                width: 344px;
                height: 110px;
            }
            
            .storefront-3-0-0-0-0-0-0 {
                display: flex;
                flex-grow: 1;
            }
            
            .storefront-repeat_popular_libraries-0 {
                display: flex;
                flex-direction: column;
                flex-grow: 1;
            }
            
            .storefront-3-0-0-0-0-0-0-0-0-0 {
                display: flex;
                flex-shrink: 0;
                padding-right: 32px;
            }
            
            .storefront-popular_libraries-3 {
                flex-shrink: 0;
                display: flex;
                flex-direction: column;
                min-width: 312px;
            }
            
            .storefront-3-0-0-0-1 {
                height: 0px;
                flex-grow: 1;
                flex-basis: 0px;
            }
            
            .storefront-3-0-0-1 {
                width: 0px;
                flex-shrink: 0;
                flex-grow: 1;
                flex-basis: 0px;
            }
            
            .storefront-4 {
                display: flex;
                flex-shrink: 0;
                padding-left: 20px;
                padding-right: 20px;
            }
            
            .storefront-libraries_from_your_team_-7 {
                width: 764px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 36px;
                line-height: 41px;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .storefront-5 {
                display: flex;
                flex-shrink: 0;
                padding-right: 20px;
            }
            
            .storefront-rectangle_11 {
                height: 170px;
                flex-grow: 1;
                flex-basis: 0px;
                overflow: scroll;
                position: relative;
                background: rgba(255, 255, 255, 0);
            }
            
            .storefront-5-0-0 {
                display: flex;
                flex-direction: column;
                flex-grow: 1;
                padding-top: 20px;
                position: absolute;
                width: 100%;
                min-height: 100%;
            }
            
            .storefront-5-0-0-0 {
                display: flex;
                flex-shrink: 0;
                padding-left: 20px;
            }
            
            .storefront-5-0-0-0-0-0 {
                display: flex;
            }
            
            .storefront-repeat_team_libraries-3 {
                display: flex;
                flex-direction: column;
                flex-grow: 1;
            }
            
            .storefront-5-0-0-0-0-0-0-0-0 {
                display: flex;
                flex-shrink: 0;
                padding-right: 32px;
            }
            
            .storefront-publiclibrary-7 {
                flex-shrink: 0;
                display: flex;
                flex-direction: column;
                min-width: 312px;
            }
            
            .storefront-5-0-0-0-1 {
                height: 0px;
                flex-grow: 0;
                flex-basis: 0px;
            }
            
            .storefront-optional_build_your_own-7 {
                display: flex;
                flex-direction: column;
            }
            
            .storefront-5-0-0-0-2-0 {
                display: flex;
                flex-shrink: 0;
                padding-right: 30px;
            }
            
            .storefront-createlibrarycard_instance-5 {
                flex-shrink: 0;
                display: flex;
                flex-direction: column;
            }
            
            .storefront-5-0-0-0-3 {
                height: 0px;
                flex-grow: 1;
                flex-basis: 0px;
            }
            
            .storefront-5-0-0-1 {
                width: 0px;
                flex-shrink: 0;
                flex-grow: 1;
                flex-basis: 0px;
            }
            
            .storefront-6 {
                display: flex;
                flex-shrink: 0;
                padding-left: 20px;
                padding-right: 20px;
            }
            
            .storefront-design_develop_publish_-1 {
                width: 764px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 36px;
                line-height: 41px;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .storefront-7 {
                display: flex;
                flex-shrink: 0;
                margin-top: 20px;
                padding-left: 20px;
                padding-right: 20px;
            }
            
            .storefront-_you_can_design_and_develop_components_either_in_code_or_inside_pagedraw_take_a_look_at_developer_documentation_for_more_details_-8 {
                width: 764px;
                flex-shrink: 0;
                font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
                color: #000000;
                font-size: 14px;
                line-height: 16px;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .storefront-8 {
                width: 0px;
                flex-shrink: 0;
                flex-grow: 1;
                flex-basis: 0px;
            }
            
            * {
                box-sizing: border-box;
            }
            
            body {
                margin: 0;
            }
            
            button:hover {
                cursor: pointer;
            }
            
            a {
                text-decoration: none;
                color: inherit;
            }
            
            .pd-onhover-parent >.pd-onhover {
                display: none;
            }
            
            .pd-onhover-parent:hover > * {
                display: none;
            }
            
            .pd-onhover-parent:hover > .pd-onhover {
                display: flex;
            }
            
            .pd-onactive-parent > .pd-onactive {
                display: none;
            }
            
            .pd-onactive-parent:active > * {
                display: none;
            }
            
            .pd-onactive-parent:active > .pd-onactive {
                display: flex;
            }
            
            .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
                display: none;
            }
        """} /> 
        <div className="storefront-0">
            <div className="storefront-0-0">
                <div className="storefront-0-0-0">
                    <div className="storefront-icon-7" /> 
                </div>
            </div>
            <div className="storefront-library_store_-5">
                Library Store
            </div>
        </div>
        <div className="storefront-1">
            <div className="storefront-pagedraw_libraries_allow_you_to_import_existing_react_libraries_straight_into_pagedraw_just_find_a_widget_or_component_library_you_like_add_the_library_to_your_project_and_you_are_ready_to_go_-1">
                Pagedraw Libraries allow you to import existing React libraries straight into Pagedraw. Just find a widget or component library you like, add the library to your project and you are ready to go.
            </div>
        </div>
        <div className="storefront-2">
            <div className="storefront-popular_libraries_-5">
                Popular Libraries
            </div>
        </div>
        <div className="storefront-3">
            <div className="storefront-rectangle_1">
                <div className="storefront-3-0-0">
                    <div className="storefront-3-0-0-0">
                        <div className="storefront-3-0-0-0-0">
                            { if (@props.popularLibraries.length > 0)
                                <div className="storefront-3-0-0-0-0-0-0">
                                    { (@props.popularLibraries).map (lib, i) =>
                                        <div key={i} className="storefront-repeat_popular_libraries-0">
                                            <div className="storefront-3-0-0-0-0-0-0-0-0-0">
                                                <div className="storefront-popular_libraries-3">
                                                    <Publiclibrary title={lib.title} version={lib.version} owner={lib.owner} installCount={lib.installCount} starCount={lib.starCount} installed={lib.installed} repository={lib.repository} onDetails={lib.onDetails} onInstall={lib.onInstall} starred={lib.starred} /> 
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            }
                        </div>
                        <div className="storefront-3-0-0-0-1" /> 
                    </div>
                    <div className="storefront-3-0-0-1" /> 
                </div>
            </div>
        </div>
        <div className="storefront-4">
            <div className="storefront-libraries_from_your_team_-7">
                Libraries from your team
            </div>
        </div>
        <div className="storefront-5">
            <div className="storefront-rectangle_11">
                <div className="storefront-5-0-0">
                    <div className="storefront-5-0-0-0">
                        { if (@props.teamLibraries.length > 0)
                            <div className="storefront-5-0-0-0-0-0">
                                { (@props.teamLibraries).map (lib, i) =>
                                    <div key={i} className="storefront-repeat_team_libraries-3">
                                        <div className="storefront-5-0-0-0-0-0-0-0-0">
                                            <div className="storefront-publiclibrary-7">
                                                <Publiclibrary title={lib.title} version={lib.version} owner={lib.owner} installCount={lib.installCount} starCount={lib.starCount} installed={lib.installed} repository={lib.repository} onDetails={lib.onDetails} onInstall={lib.onInstall} starred={lib.starred} /> 
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        }
                        <div className="storefront-5-0-0-0-1" /> 
                        <div className="storefront-optional_build_your_own-7">
                            <div className="storefront-5-0-0-0-2-0">
                                <div className="storefront-createlibrarycard_instance-5">
                                    <Createlibrarycard onClick={(@props.onCreateNewLibrary)} /> 
                                </div>
                            </div>
                        </div>
                        <div className="storefront-5-0-0-0-3" /> 
                    </div>
                    <div className="storefront-5-0-0-1" /> 
                </div>
            </div>
        </div>
        <div className="storefront-6">
            <div className="storefront-design_develop_publish_-1">
                {"Design, Develop & Publish"}
            </div>
        </div>
        <div className="storefront-7">
            <div className="storefront-_you_can_design_and_develop_components_either_in_code_or_inside_pagedraw_take_a_look_at_developer_documentation_for_more_details_-8">
                <div> You can design and develop components either in code or inside Pagedraw.</div>
                <br/>
                <div>Take a look at developer documentation for more details.</div>
            </div>
        </div>
        <div className="storefront-8" /> 
    </div>

module.exports = (props) -> render.apply({props})
